/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class nativeIO_NativeIO */

#ifndef _Included_nativeIO_NativeIO
#define _Included_nativeIO_NativeIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeIO_NativeIO
 * Method:    getCh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativeIO_NativeIO_getCh
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
